### ISSUE TITLE
Support v2ray plugin

### ISSUE THREAD

**Issue by omidraha** [XWJACK/Shadowrocket#4]
Hi,
Is this support v2ray plugin?
Is there any IPA released file for this?
Thanks.

**Comment by XWJACK** [comment]
It's just a hook application for Shadowrocket, the same as the original version.
You need an iOS developer account to run and install to the phone.

**Comment by omidraha** [comment]
I don't have iOS developer account, it's possible to release an IPA file for that? 
something like this [one](https://github.com/Virtue86/Shadowrocket---iOS-ipa)?

**Comment by XWJACK** [comment]
![image](https://user-images.githubusercontent.com/15156226/63750046-460c8a80-c8df-11e9-909f-ed31b39dd845.png)

https://github.com/XWJACK/Shadowrocket

**Comment by omidraha** [comment]
> ![image](https://user-images.githubusercontent.com/15156226/63750046-460c8a80-c8df-11e9-909f-ed31b39dd845.png)
> 
> https://github.com/XWJACK/Shadowrocket

I don't understand what you said,

**Comment by omidraha** [comment]
> ![image](https://user-images.githubusercontent.com/15156226/63750046-460c8a80-c8df-11e9-909f-ed31b39dd845.png)
> 
> https://github.com/XWJACK/Shadowrocket

I translate it.
Thanks !
